### ISSUE TITLE
Improve driver exception translation

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-springdata#23]
Spring Data has its own hierarchy of exceptions converted from the underlying data layer exceptions. We need to classify the driver exceptions and rewrite `DefaultTarantoolExceptionTranslator`.

**Comment by sharonovd** [comment]
Probably done already

**Comment by lexasub** [comment]
> Spring Data has its own hierarchy of exceptions converted from the underlying data layer exceptions. We need to classify the driver exceptions and rewrite `DefaultTarantoolExceptionTranslator`.

may be you want close issue
