### ISSUE TITLE
Add integer to floating point value converters

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-springdata#34]
The following converters are necessary, since MessagePack reduces the numbers to the smallest value, and there is no `double` type in Tarantool 1.10:

 - Short -> Double, Short -> Float
 - Integer -> Double, Integer -> Float
 - Long -> Double

**Comment by vrogach2020** [comment]
Seems to be fixed in https://github.com/tarantool/cartridge-java/pull/114
