### ISSUE TITLE
Flaky tests for BookRespository

### ISSUE THREAD

**Issue by akudiyar** [tarantool/cartridge-springdata#39]
See the last run results 
https://github.com/tarantool/cartridge-springdata/actions/runs/664124454

**Comment by vrogach2020** [comment]
Most likely reason of this tests flakin is that crud reads data from replica before they have been replicated there.
Need to reproduce this case and check.
If so the following workaraound retrying method for selects can be used:
```java

public class FlakyTestWa {

    public static <T> Optional<T> execWithRetry(int tries, Supplier<Optional<T>> fn) {
        Optional<T> result;
        int c = 0;
        do {
            result = fn.get();
        } while (c < tries && !result.isPresent());
        return result;
    }
}


```

**Comment by vrogach2020** [comment]
Should be fixed by https://github.com/tarantool/cartridge-springdata/commit/b230551938351152fe786b59e86fc2a083d397cc
