### ISSUE TITLE
Add tests name convention and change tests to this convention

### ISSUE THREAD

**Issue by wey1and** [tarantool/cartridge-springdata#47]
I suggest the following convention: 
Tests names should be correspond the next pattern:

**test_[methodName/scenarioName]_should[Action]_if[Condition]**

**[methodName/scenarioName]_ - is optional.**
**if[Condition] - is optional. You can omit this if the execution is straightforward.**

Also, inside the body of the test there should be comments of the following format:
```   
    //given
    [some code that defines conditions]
    //when
    [some code that executes the test case]
    //then
    [some code with assertions]
```

Example: 
If we have method like this:

```java   
    public String hello(String name) {
        return "Hello, " + name;
    }
```

Test for this method:
```java
    @Test
    public void test_hello_shouldReturnHelloWithName() {
        //given
        String name = "John";
        
        //when
        String welcome = hello(name);
        
        //then
        assertThat(welcome).isEqualTo("Hello, John");
    }
```

If we have method like this:
```java
    public String helloWithCondition(@Nullable String name) {
        if (name == null) {
            return "Hello Stranger";
        }
        return "Hello, " + name;
    }
```

Test for this method can be like this:
```java
    @Test
    public void test_helloWithCondition_shouldReturnHelloStranger_ifNameIsNull() {
        //given
        String name = null;

        //when
        String welcome = helloWithCondition(name);

        //then
        assertThat(welcome).isEqualTo("Hello, Stranger");
    }
```

It's good when this pattern can be included into test method name but it's not always possible.
When the description is too large then test case can contain additional info in comment. 
Also consider this points:

 - Name of test method must not violate linter rules and generate compiler warnings (must not contain special characters, be longer than 120 chars etc).
 - These points of test case must be readable and simple:
    - test object (class, method)
    - action (input)
    - expected reaction of system (output)
- Do not perform a total refactoring of existing codebase.
Just leave the code better than it was after making changes.

**Comment by akudiyar** [comment]
Thank you for the proposal!

I suggest using only `test_` for method prefixes instead of some names, the test method name already includes the "shouldSomething" part which describes it.

**Comment by wey1and** [comment]
> Thank you for the proposal!
> 
> I suggest using only `test_` for method prefixes instead of some names, the test method name already includes the "shouldSomething" part which describes it.

Done

**Comment by vrogach2020** [comment]
I'll try to finalize the agreement:

1 Name of test method must not violate linter rules and 
generate compiler warnings (must not contain special characters, be longer than 120 chars etc).

2 These points of testcase must be readable and simple:
 - test object (class, method)
 - action (input)
 - expected reaction of system (output)

It's good when they can be included into test method name but it's not always possible.
When the description is too large then testcase should contain a comment on points mentioned above.

3 Do not perform a total refactoring of existing codebase.
Just leave the code better than it was after making changes.

**Comment by vrogach2020** [comment]
Also maybe use this pattern ? 
```
test_[method]_when[condition]_then[reaction]
For example:
test_helloWorld_whenCalled_ThenPrintHelloWorld()
```

**Comment by wey1and** [comment]
Thanks to all! 
Based on the discussion, I brought the initial version to the final one.
