### ISSUE TITLE
Truncate doesn't work for RetryingTarantoolClient

### ISSUE THREAD

**Issue by ArtDu** [tarantool/cartridge-springdata#70]
There is a line that this is a temporary hack, but in order not to lose and forget, I will add a ticket for this problem

https://github.com/tarantool/cartridge-springdata/blob/5e06e8f9ff6f5311c3ed7641fb71f40fb36937e5/src/main/java/org/springframework/data/tarantool/core/BaseTarantoolTemplate.java#L187-L200

**Comment by vrogach2020** [comment]
Since truncate was implemented we now can remove this clutch:

https://github.com/tarantool/cartridge-java/blob/master/src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java#L96
